### ISSUE TITLE
Twitter API call needs deprecating 

### ISSUE THREAD

**Issue by portableant** [FitzwilliamMuseum/fitz-main-website#565]
A daily cron job runs in the console/kernel.php file this can be found at https://github.com/FitzwilliamMuseum/fitz-main-website/blob/master/app/Console/Kernel.php#L54
Following the API changes from Twitter the FitzWebsite application has been suspended for violation of t&c (got the email today from their robot admin) and therefore this call will fail. 

Commenting out or removing the line will do the trick, you don't need to remove the code from the codebase that calls the API and then makes the solr import. 
Twitter was good once.

**Comment by simonrjones** [comment]
Thanks, I noticed the API dropped read access completely recently. Will review this later this week (after our office move!)
